X01BD: Remove timeservice_app_cert certificate
* This cert was removed in R qcom sepolicy...

[poad42]: use platform instead
error: vendor/oneplus/msm8998-common/Android.bp:265:1: "TimeService" depends on undefined module "timeservice_app_cert-legacy-um"